# Generated by Django 4.2.6 on 2023-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default='asd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
